
###
// CREATE A VEHICLE (with auth)
POST http://localhost:8080/vehicle/createVehicle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImFsaWNlQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiQ0xJRU5UIiwidXNlcklkIjoxMiwiZXhwIjoxNjk3NjQ5OTE3fQ.1cqUFnY2_YUbk_UequP8W9W2jifMvE82Bco95CzzNKE

{
  "brand": "Ford",
  "model": "Focus",
  "year": 2021,
  "vehicleClass": "Test",
  "engineType": "ICE",
  "licensePlate": "qql-sl-11",
  "imgLink": "https://www.google.com",
  "vehicleLocation": "Test",
  "price": 250.00,
  "availability": "Test"
}

###
// GET VEHCILE BY ID (STAFF and CLIENT only with auth)

GET http://localhost:8080/vehicle/6
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImFsaWNlQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiQ0xJRU5UIiwidXNlcklkIjoxMiwiZXhwIjoxNjk3NjQ5OTE3fQ.1cqUFnY2_YUbk_UequP8W9W2jifMvE82Bco95CzzNKE

###
// GET ALL VEHICLES (STAFF and CLIENT only with auth)

GET http://localhost:8080/vehicle/all
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN1cGVyQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjEzLCJleHAiOjE2OTc2NDk5MTd9.0vHrvVtve2dQQ_1ELBZ0iGx0zxkgBpyqY2GNwqJJeGI

###
// GET VEHCILES BY USER ID with auth

GET http://localhost:8080/vehicle/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImFsaWNlQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiQ0xJRU5UIiwidXNlcklkIjoxMiwiZXhwIjoxNjk3NjQ5OTE3fQ.1cqUFnY2_YUbk_UequP8W9W2jifMvE82Bco95CzzNKE

###

// UPDATE VEHCILES BY ID without auth

PUT http://localhost:8080/vehicle/1
Content-Type: application/json

{
  "userId": 3,
  "brand": "Toyota",
  "model": "Camry",
  "year": 2022,
  "vehicleClass": "Sedan",
  "engineType": "ICE",
  "licensePlate": "AB-C1-23",
  "imgLink": "car-image.jpg",
  "vehicleLocation": "New York",
  "price": 250.0,
  "availability": "donderdag"
}

###
// DELETE VEHICLE without auth
DELETE http://localhost:8080/vehicle/3
Accept: application/json

###
