// GET ALL RENTALS (STAFF)
GET http://localhost:8080/rental/allRentals
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDVAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjYsImV4cCI6MTY5NzgxNDU5M30.8DYSJuaPwgoqkVjEn4kFwFEbSvVo_3xKg_XW6UA5SFo

###
// GET RENTALS FROM USERID FROM JWT TOKEN
GET http://localhost:8080/rental/rentals
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDRAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjgsImV4cCI6MTY5NzcyMzI4Nn0.396ATjnoQ30pupIOZ6K1o1eGuBMNKwMpcGvQ8xlHDes

###
// CREATE A RENTAL WITH {VEHICLEID} (userType: STAFF)
POST http://localhost:8080/rental/createRental/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDVAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjYsImV4cCI6MTY5NzgyMTY5OH0.eCPNn2Yl21e-8AE8YzqrskScqe6MLRDhRmTXiwKuvvk

{
  "date": "2023-11-19"
}

###
// CREATE A VEHICLE (with auth)
POST http://localhost:8080/vehicle/createVehicle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDVAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjYsImV4cCI6MTY5NzgyMTY5OH0.eCPNn2Yl21e-8AE8YzqrskScqe6MLRDhRmTXiwKuvvk

{
  "brand": "Tesla",
  "model": "Model S",
  "year": 2023,
  "vehicleClass": "Test",
  "engineType": "BEV",
  "licensePlate": "04-ALF-18",
  "imgLink": "https://www.google.com",
  "latitude": 51.571915,
  "longitude": 4.768323,
  "price": 250.00,
  "availability": true
}

###
// GET VEHCILE BY ID (STAFF and CLIENT only with auth)
GET http://localhost:8080/vehicle/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudEBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6IkNMSUVOVCIsInVzZXJJZCI6MSwiZXhwIjoxNjk3NjY1MjgzfQ.5cw1MAmTNDplg-TOUJWPU8HQ8_6zBooB1My3_s4q23Y

###
// Set vehicle availability (STAFF and CLIENT only with auth)
PUT http://localhost:8080/vehicle/setAvailability/7/true
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDNAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjcsImV4cCI6MTY5NzcyMzI4Nn0.S4pjCk4G4R2TgcKhhtV3wbXtaky_TXr-zTwX0MO9q7A

###
// GET ALL AVAILABLE VEHICLES (STAFF and CLIENT only with auth)
GET http://localhost:8080/vehicle/allAvailable
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDJAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjYsImV4cCI6MTY5NzcyMzI4Nn0.On96huWPPLcAMlqNgJX-XhZncAqu2BEiFrwJiVGMajE

###
// GET ALL VEHICLES (Client)
GET http://localhost:8080/vehicle/all
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDNAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjcsImV4cCI6MTY5NzcyMzI4Nn0.S4pjCk4G4R2TgcKhhtV3wbXtaky_TXr-zTwX0MO9q7A

###
// GET VEHCILES BY USER ID FROM JWT
GET http://localhost:8080/vehicle/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjMsImV4cCI6MTY5NzcyMzI4Nn0.I2neXUImh89jYcRPmCNWERAWK7lUW2inLjSc-T9JtLs

###
// UPDATE VEHCILES BY ID with auth
PUT http://localhost:8080/vehicle/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDVAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjYsImV4cCI6MTY5NzgxNDU5M30.8DYSJuaPwgoqkVjEn4kFwFEbSvVo_3xKg_XW6UA5SFo

{
  "userId": 12,
  "brand": "super alice Toyota",
  "model": "Camry",
  "year": 2022,
  "vehicleClass": "Sedan",
  "engineType": "ICE",
  "licensePlate": "AB-C1-30",
  "imgLink": "car-image.jpg",
  "latitude": 51.559520251527005,
  "longitude": 4.661058457551144,
  "price": 250.0,
  "availability": true
}

###
// DELETE OWN VEHICLE (Client)
DELETE http://localhost:8080/vehicle/9
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDVAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjksImV4cCI6MTY5NzcyMzI4Nn0.qNLbILPPB2EMftDV7lag8o4k8GKwS8q_cxCDlHyqud0

###
// DELETE USER FROM JWT TOKEN (userType: all)
DELETE http://localhost:8080/user/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDJAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjYsImV4cCI6MTY5NzcyMzI4Nn0.On96huWPPLcAMlqNgJX-XhZncAqu2BEiFrwJiVGMajE

###
// Update user from userId in JWT token (userType: CLIENT)
PUT http://localhost:8080/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDJAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjEsImV4cCI6MTY5NzcyMTMzMn0.5tC-aNjHs0wgAnk9Hk0jeiuGjqgdm2XCnesq32uM1Hg

{"email": "client2@email.com",
  "userType": "CLIENT",
  "password": "password123",
  "firstName": "test",
  "lastName": "test",
  "phone": "+79999999999",
  "street": "street",
  "buildingNumber": "211",
  "zipCode": "4818CR",
  "city": "Breda"
}

###
// Get user info from userId inside JWT token (userType: CLIENT)
GET http://localhost:8080/user/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudEBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6IkNMSUVOVCIsInVzZXJJZCI6NSwiZXhwIjoxNjk3NzIzMjg2fQ.B1PgcH3gKNd3AkLK8qTANpmeGsMFEWAPcaX0mQUz5ns

###
// Delete user (userType: STAFF)
DELETE http://localhost:8080/user/7
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjQsImV4cCI6MTY5NzcyMzI4Nn0.B3Z1ETklwUO6jWFDG778EHCH3eBAbSGoaHxZLA-ggs8

###
// Update user (userType: STAFF)
PUT http://localhost:8080/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjIsImV4cCI6MTY5NzcyMTMzMn0.AzUL1BsdgqqnDo-IFkQB-t6lqmumlJp62htQH_MVhFQ

{"email": "client2@email.com",
  "userType": "CLIENT",
  "password": "password123",
  "firstName": "firstName",
  "lastName": "lastName",
  "phone": "+79999999999",
  "street": "address",
  "buildingNumber": "1",
  "zipCode": "4818CR",
  "city": "Breda"
}

###
// Get user by userId (userType: STAFF)
GET http://localhost:8080/user/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjIsImV4cCI6MTY5NzcyMTMzMn0.AzUL1BsdgqqnDo-IFkQB-t6lqmumlJp62htQH_MVhFQ

###
// Get all users (userType: STAFF)
GET http://localhost:8080/user/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjMsImV4cCI6MTY5NzgxOTM3OH0.mV0-KjqyG6S3YNxM8nZXtuIKwRuPQohd0Z2gKo8Fnvo

###
// Authenticate a user (no auth)
POST http://localhost:8080/user/signin
Content-Type: application/json

{
  "email": "client5@email.com",
  "password": "StrongPassword1!"
}

###
// Register a new user (no auth)
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "email": "client5@email.com",
  "userType": "CLIENT",
  "password": "StrongPassword1!"
}

###