// CREATE A RENTAL WITH {VEHICLEID} (userType: STAFF)
POST http://localhost:8080/rental/createRental/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODgwODAvIiwiZW1haWwiOiJjbGllbnRAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjIsImV4cCI6MTY5NzM4NTA4Nn0.dDrpBTo17hARw9k8NyULadxuhpfXwOKf-K7NquVw9nI

{
  "date": "",
  "price": 100.00,
  "location": "Test",
  "status": "MakeThisAnEnum",
  "distanceTravelled": 0.00,
  "score": 100
}

###
// CREATE A VEHICLE (userType: STAFF)
POST http://localhost:8080/vehicle/createVehicle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODgwODAvIiwiZW1haWwiOiJjbGllbnRAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjIsImV4cCI6MTY5NzM4NTA4Nn0.dDrpBTo17hARw9k8NyULadxuhpfXwOKf-K7NquVw9nI

{
  "brand": "Ford",
  "model": "Focus",
  "year": 2021,
  "vehicleClass": "Test",
  "engineType": "Diesel",
  "licensePlate": "CC-AA-00",
  "imgLink": "https://www.google.com",
  "vehicleLocation": "Test",
  "price": 250.00,
  "availability": "Test"
}

###
// DELETE USER FROM JWT TOKEN (userType: all)
DELETE http://localhost:8080/user/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODgwODAvIiwiZW1haWwiOiJzdGFmZkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InN0YWZmIiwidXNlcklkIjoxLCJleHAiOjE2OTY4NjAxODd9.nSGUxbZncvqHp74BFFQC_6UgWKkLBoDVRice52MOD00

###
// UPDATE USER FROM JWT TOKEN (userType: all)
PUT http://localhost:28852/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6Mjg4NTIvIiwiZW1haWwiOiJzdGFmZjNAZW1haWwuY29tIiwidXNlclR5cGUiOiJzdGFmZiIsInVzZXJJZCI6MTAsImV4cCI6MTY5NjY3OTYzMn0.w2TiAuK9Zd9KIfpy_S0Tcya5IU--xnsBwidlos7TsYA

{"email": "staff3@email.com",
  "userType": "staff",
  "password": "password123",
  "name": "test",
  "phone": "+79999999999",
  "address": "address"}

###
// GET USER INFO FROM JWT TOKEN (userType: all)
GET http://localhost:8080/user/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODgwODAvIiwiZW1haWwiOiJzdGFmZkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InN0YWZmIiwidXNlcklkIjoxLCJleHAiOjE2OTY4NjAxODd9.nSGUxbZncvqHp74BFFQC_6UgWKkLBoDVRice52MOD00

###
// DELETE USER (userType: STAFF)
DELETE http://localhost:8080/user/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODgwODAvIiwiZW1haWwiOiJhbGV4MkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InN0YWZmIiwidXNlcklkIjozLCJleHAiOjE2OTcyMDUyNjZ9.MvI3hdIt3evMiHsyXh7uympxUuN-Jj14gl-4O4qpgBM

###
// UPDATE USER (userType: STAFF)
PUT http://localhost:8080/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODgwODAvIiwiZW1haWwiOiJhbGV4QGVtYWlsLmNvbSIsInVzZXJUeXBlIjoic3RhZmYiLCJ1c2VySWQiOjEsImV4cCI6MTY5Njk0NzA2OH0.RLKl1ketWrLhHPED5h0nBvCbaE6FQId9NR_oMFVvci8

{"email": "lex@email.com",
  "userType": "staff",
  "password": "password123",
  "firstName": "firstName",
  "lastName": "lastName",
  "phone": "+79999999999",
  "street": "address",
  "buildingNumber": "1",
  "zipCode": "4818CR",
  "city": "Breda"
}

###
// GET USER BY ID (userType: STAFF)
GET http://localhost:8080/user/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODgwODAvIiwiZW1haWwiOiJzdGFmZkBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6InN0YWZmIiwidXNlcklkIjoxLCJleHAiOjE2OTY4NjAxODd9.nSGUxbZncvqHp74BFFQC_6UgWKkLBoDVRice52MOD00

###
// GET ALL USERS (userType: STAFF)
GET http://localhost:8080/user/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDNAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjEsImV4cCI6MTY5NzY0OTA2N30.A3ddLU67cTA5UWlB29Pg-3561B1GVP1RItUwNt3UvUI

###
// AUTHENTICATE USER (no auth)
POST http://localhost:8080/user/signin
Content-Type: application/json

{
  "email": "super@email.com",
  "password": "StrongPassword1!"
}

###
// REGISTER USER (no auth)
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "email": "super@email.com",
  "userType": "STAFF",
  "password": "StrongPassword1!"
}

###