// HTTP Requests for RenalRoutes.kt

###
// 18. Create a rental with vehicleId (userType: STAFF)
POST http://localhost:8080/rental/createRental/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImZpYXRyZW50ZXJAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjI2LCJleHAiOjE2OTc4Mzc2ODR9.PBtQB51vJUKf8dpTjR3KZIEcPALlRmfDz6xaj4pVeDI

{
  "date": "2023-11-27"
}

###
// 19. Get rentals from userId from JWT token (userType: CLIENT)
GET http://localhost:8080/rental/rentals
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDMyQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiQ0xJRU5UIiwidXNlcklkIjoyMCwiZXhwIjoxNjk3ODM1NTAwfQ.XHaTPxEn0zvZKR9G0D6aMUfPZvcPlKEWDawO4OBuYlI

###
// 20. Get rental by rentalId (userType: CLIENT)
GET http://localhost:8080/rental/14
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDMyQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiQ0xJRU5UIiwidXNlcklkIjoyMCwiZXhwIjoxNjk3ODM1NTAwfQ.XHaTPxEn0zvZKR9G0D6aMUfPZvcPlKEWDawO4OBuYlI

###
// 21. Get my rentals for vehicle with vehicleId (renter perspective) (userType: CLIENT)
GET http://localhost:8080/rental/rentedVehicle/6
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDMyQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiQ0xJRU5UIiwidXNlcklkIjoyMCwiZXhwIjoxNjk3ODM1NTAwfQ.XHaTPxEn0zvZKR9G0D6aMUfPZvcPlKEWDawO4OBuYlI

###
// 22. Get rentals for my vehicle with vehicleId (owner perspective) (userType: CLIENT)
GET http://localhost:8080/rental/ownedVehicle/7
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImZpYXRvd25lckBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6IkNMSUVOVCIsInVzZXJJZCI6MjUsImV4cCI6MTY5NzgzNzY4NH0.BvCfDBCcqejdi_wkRpDMAPEd5B5AFIlwBEX3XBxMvJc

###
// 23. Get all rentals (userType: STAFF)
GET http://localhost:8080/rental/allRentals
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjIsImV4cCI6MTY5Nzg0MDgyOH0.C5_-xroeIRybw9MdxKHhWe8qZv3q_Jm7MBdxHWS3rhE

###
// 24. Update rentalStatus by rentalId (Approved/Denied for vehicle owner, Cancelled for rental owner)
GET http://localhost:8080/rental/status/14?status=denied
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImZpYXRvd25lckBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6IkNMSUVOVCIsInVzZXJJZCI6MjUsImV4cCI6MTY5Nzg0MDgyOH0.qxhHEYy8UOjeqC2DmkP9i-2uqJZbk-f0avz2i69AN8s

###
// 25. Update rental by rentalId (userType: STAFF)
PUT http://localhost:8080/rental/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImZpYXRyZW50ZXJAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjI2LCJleHAiOjE2OTc4Mzc2ODR9.PBtQB51vJUKf8dpTjR3KZIEcPALlRmfDz6xaj4pVeDI

{"vehicleId": 7,
  "userId": 26,
  "date": "2023-01-01",
  "price": 129.00,
  "latitude": 51.571915,
  "longitude": 4.768323,
  "status": "APPROVED",
  "distanceTravelled": 5.00,
  "score": 100
}

###
// 26. Delete rental by rentalId (userType: CLIENT - owner of rental)
DELETE http://localhost:8080/rental/14
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImZpYXRyZW50ZXJAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjI2LCJleHAiOjE2OTc4NDEzNzV9.x8tM71O_bPTA6TuVySyhI5kyZr5P8tVAlbCb2kOAfdA

###
// 27. Delete rental by rentalId (userType: STAFF)
DELETE http://localhost:8080/rental/staff/13
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjIsImV4cCI6MTY5Nzg0MTM3NX0.p3k-79xzggMqE6VCwQ718UljAe2BmVj3POx2usbJ7iM


