// HTTP Requests for VehicleRoutes.kt

###
// 10. Create a vehicle (userType: CLIENT)
POST http://localhost:8080/vehicle/createVehicle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImZpYXRvd25lckBlbWFpbC5jb20iLCJ1c2VyVHlwZSI6IkNMSUVOVCIsInVzZXJJZCI6MjUsImV4cCI6MTY5NzgzNzY4NH0.BvCfDBCcqejdi_wkRpDMAPEd5B5AFIlwBEX3XBxMvJc

{
  "brand": "Tesla",
  "model": "Model S",
  "year": 2023,
  "vehicleClass": "Test",
  "engineType": "BEV",
  "licensePlate": "04-ALF-55",
  "imgLink": "https://www.google.com",
  "latitude": 51.571915,
  "longitude": 4.768323,
  "price": 250.00,
  "availability": true
}

###
// 11. Get vehicle by ID (userType: CLIENT)
GET http://localhost:8080/vehicle/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDNAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjE5LCJleHAiOjE2OTc4MzQyNDJ9.yLE0BuivNgexNWc2B9SYOEMWkXwlx5M1WJHWqkKNR0s


###
// 12. Get all vehicles (userType: STAFF)
GET http://localhost:8080/vehicle/all
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjIsImV4cCI6MTY5NzgzNzY4NH0.OUlVHzhqryPw6_IPE4tUjtr-FAYcMa6YoRMgQp47VK8

###
// 13. Get all available vehicles (userType: CLIENT)
GET http://localhost:8080/vehicle/allAvailable
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjIsImV4cCI6MTY5NzgzNzY4NH0.OUlVHzhqryPw6_IPE4tUjtr-FAYcMa6YoRMgQp47VK8

###
// 14. Get vehicles by userId from JWT token (userType: CLIENT)
GET http://localhost:8080/vehicle/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDMyQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiQ0xJRU5UIiwidXNlcklkIjoyMCwiZXhwIjoxNjk3ODM0MjQyfQ.oWhNXH013ZdnkkbIpJJ2JFZmGEzcPyo4Rjs76rbkW5o

###
// 15. Update vehicles by ID (userType: CLIENT)
PUT http://localhost:8080/vehicle/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDMyQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiQ0xJRU5UIiwidXNlcklkIjoyMCwiZXhwIjoxNjk3ODM0MjQyfQ.oWhNXH013ZdnkkbIpJJ2JFZmGEzcPyo4Rjs76rbkW5o

{
  "brand": "Toyota",
  "model": "Camry",
  "year": 2022,
  "vehicleClass": "Sedan",
  "engineType": "ICE",
  "licensePlate": "AB-C1-30",
  "imgLink": "car-image.jpg",
  "latitude": 51.559520,
  "longitude": 4.661058,
  "price": 250.0,
  "availability": true
}

###
// 16. Set vehicle availability (userType: CLIENT)
PUT http://localhost:8080/vehicle/setAvailability/3/true
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6ImNsaWVudDJAZW1haWwuY29tIiwidXNlclR5cGUiOiJDTElFTlQiLCJ1c2VySWQiOjIxLCJleHAiOjE2OTc4MzU1MDB9.kJrSLzD3NyvKumSJ_Jti1WH-XGysT-On6EEoWDi27w8


###
// 17. Delete own vehicle (userType: CLIENT)
DELETE http://localhost:8080/vehicle/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJlbWFpbCI6InN0YWZmQGVtYWlsLmNvbSIsInVzZXJUeXBlIjoiU1RBRkYiLCJ1c2VySWQiOjIsImV4cCI6MTY5Nzg0MTM3NX0.p3k-79xzggMqE6VCwQ718UljAe2BmVj3POx2usbJ7iM

